### PR TITLE
new take on Fig #1

### PR DESCRIPTION
**Pull request by jordansread**
image

### CODE REVIEW

**Comment by jordansread** [comment]
This fig is in the sandbox, not the app right now.

**Comment by jordansread** [comment]
mobile version:
image

idea being that the desktop version drops the js table, but the mobile version keeps it because it has the additional content that is chopped out of the mobile version. 

@ldecicco-USGS can you review?

**Comment by ldecicco-USGS** [comment]
Looks cool. Can we move it to the real thing?

**Comment by jordansread** [comment]
want me to code it up? @ldecicco-USGS if so, can you create an issue for it and assign to me?

**Pull request merged**
