### PR TITLE
new figure 1

### PR DESCRIPTION
**Pull request by jordansread**
Taking some major shortcuts on the data dependency for this one, but doing so for time limits. The original geometry is built from the data, and I grabbed that geometry and did some direct edits to the svg to get the syle right. Now it is templated for mobile and desktop, but is not impacted by changes to the source data. We can tackle that later if it is a priority. 

Looks like this now: 
image
default is to have that one tab expanded when you load the app, and then it collapses if you mouseover anything else.

### CODE REVIEW

**Comment by jordansread** [comment]
@ldecicco-USGS try this out?

**Comment by jordansread** [comment]
@mwernimont note major change to fig1.mustache

**Comment by ldecicco-USGS** [comment]
:100:

**Comment by aappling-usgs** [comment]
COOL!!!

**Pull request merged**
