### PR TITLE
fixing up text per issue #133

### PR DESCRIPTION
**Pull request by eread-usgs**

### CODE REVIEW

**Comment by eread-usgs** [comment]
did some re-arranging- someone might want to view it locally (i havent been able to do that) before merging.

**Comment by eread-usgs** [comment]
crap @ldecicco-USGS saw your un-merged PR got into making the hyperlinks live... sorry to leave a mess.... likely will be a conflict once one of these PRs gets merged.

**Comment by eread-usgs** [comment]
thanks for dealing w this, @ldecicco-USGS

**Comment by ldecicco-USGS** [comment]
It wasn't too bad. I re-ordered the references to they come in order. Can you double-check that the right reference goes with the right stat?

**Pull request merged**
